# Workflow to download and import Contoso_university_core solution to an environment using Service Principal
name: Deploy Contoso_university_core Demo

# trigger on workflow based on Pack Contoso_University_Core Demo workflow completion
on:
    workflow_run:
        workflows: ["Pack Contoso_University_Core"]
        branches: [main]
        types:
            - completed
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success'}}
        environment: Prod
        steps:
            - name: Download Artifact 
              uses: actions/download-artifact@v4
              with:
                #workflow: deploy-solution.yml
                github-token: ${{ secrets.GITHUB_TOKEN }} 
                run_id: github.event.workflow_run.id                             
            - name: Install Power Platform Tool
              uses: microsoft/powerplatform-actions/actions-install@v1.2.0
           # - name: Pack Contoso_University_core
             # uses: microsoft/powerplatform-actions/pack-solution@v1.2.0
             # with:
             #   solution-file: out/contoso_university_core.zip
             #   solution-folder: contents
              #  solution-type: Both
            - name: Import Contoso_university_Core
              uses: microsoft/powerplatform-actions/import-solution@v1.2.0
              with:
                environment-url: ${{ secrets.URL }}
                app-id: ${{ secrets.CLIENTID }}
                client-secret: ${{ secrets.SECRET }}
                tenant-id: ${{ secrets.TENANTID }}
                solution-file: out/release/contoso_university_core_managed.zip
